# file: .github/workflows/build.yml
name: build
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'temurin'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: app
      - run: ./gradlew checkstyleMain
      - run: ./gradlew test
      # - name: Publish code coverage
      #   uses: paambaati/codeclimate-action@v9.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      #     JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
      #   with:
      #     coverageCommand: make report
      #     coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco